- name: Loop Demo
  hosts: localhost
  connection: local
  tasks:
    - name: Print Vegetable Name
      ansible.builtin.debug:
        msg: Vegetable Names - {{ item }}
      loop:
        - Carrot
        - Tomato

    - name: Print Name and Quantity
      ansible.builtin.debug:
        msg: Vegetable Name - {{ item["name"] }}, Quantity - {{ item.quantity }}
      loop:
        - { name: Carrot, quantity: 100 }
        - { name: Carrot, quantity: 200 }