- name: Loop Demo
  hosts: localhost
  connection: local
  tasks:
    - name: uptime
      ansible.builtin.shell: uptime
      register: out

    - name: Print uptime
      ansible.builtin.debug:
        msg: "{{ out }}"