- name: Run Java
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load to DB
  ansible.builtin.shell: mysql -h mysql-dev.mydevops.shop -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup

