# In Ansible variables can be declared in multiple places

- name: Play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}

# Since the variable is declared on play level, then all the test access that variable. Hence, we can declare task level variables. See the example below:

- name: Play level variables
  hosts: localhost
  connection: local
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}
      vars:
        url: tasks.example.com

# Since the variable in the second example above is declared at task level, then only one task can access that variable

# The same variable can be declared from command line using -e option