# In Ansible variables can be declared in multiple places

- name: Play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}
